name: Florian Bussmann
favicon: null
layout_spectrum: 0.35446660104207695
typography_spectrum: 0.1337954537011683
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8263822470325977
  lightness: 0.3006847782526165
  saturation: 0.4544320267159492
  rhythmicContrast: 0.7369874808937311
purpose: []
